language: objective-c
osx_image: xcode9.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=curl.xcodeproj
    - IOS_FRAMEWORK_SCHEME="curl"
    - IOS_SIM_SDK=iphonesimulator11.2
    - IOS_DEV_SDK=iphoneos11.2
  matrix:
    - SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SIM_SDK"
    - SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_DEV_SDK"
script:
  - set -o pipefail
  - brew install IMcD23/brew/ibuild
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES build;

branches:
  only:
    - master
before_deploy:
  - set -o pipefail
  - carthage build --no-skip-current
  - carthage archive curl
deploy:
  provider: releases
  api_key:
    secure: VuXHR7ZMkxiPOzauG8kVyc3WkUVR0uRbNiax3J6HVBtynMI12s9M3NYZ3BgTClD1FZCDYFMFsOyRZKC9OFY09sxBtvNxrcfDCeOhTz8bNpOyTcnXuX1XKejakRnPBxJ0WpFRSgtxvPcTzsnPNbqgktmpjooIRMZWplc440ibcgn9ekrxP7fk1HUbpxfB70WCyIfd9HhKxIQDOe09FdhRbIf/rVhjzUCPOJwS4lzn/fpxijfOV107w0SjmFxalB5ND13M3AZ/ZruZ53zNrhPBup3OJKFX/lWiOZOlhcz1fxI+xBU+lPrwmY6Nx09KJ3ntfVb/9ejTEw9XI5OdqJ/cl1/NOo8fqv9BOKmuRdvTqPojaOqBDlgQxGXdHhKMwGO5Ij9QZJ609MfyFpU2lQ/XWm9vmSurH+R1hb++lfklmvIoq+vZe4L4WT8N4YskpH3RcEA6OBcxuadagHWyE9ZP3r2qkwQt8c3TR5ljZoz3wCXHZLQH3xTofH50QC15rNLaRNU5BZeawdAxmktnSPGA6lCpFdp6Hz9E+KlJwQa9Wg7mGlV3IcyxvmVe36bXujH3NPyCW1tMA/hrCHlIoQILfI927fai829Y9rrRFcSaLj7rBrcwEcmTLbR0VrutB+MAplfdYWwYzQkEQArtgYK3R68q1PyCu3dQwNJIqsp0HJc=
  file: curl.framework
  on:
    tags: true
